[package]
name = "stellar-guard"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "CLI for static security analysis of Soroban smart contracts."

[dependencies]
stellar-guard-core = { path = "../core" }
serde_json = "1"

[dev-dependencies]
serde_json = "1"
